---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: sysctl
  state_top:
    base:
      "*":
        - sysctl


platforms:
  - name: bento/debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        sysctl.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - sysctl
 
